checkpoint: 
  dir: "checkpoints"
  step: 10000

logging: 
  dir: "logs"
  step: 20

device: "cuda"


dataset_speech:
  # path: "/raid/home/rajivratn/hemant_rajivratn/librispeech/data/manifest/train-clean-100.tsv"
  path: "/raid/home/rajivratn/hemant_rajivratn/last/data/ljspeechmanifest_train.tsv"
  min_duration: 32000
  max_duration: 320000
  batch_size: &batch_size_value 64

dataset_txt:
  path: "/raid/home/rajivratn/hemant_rajivratn/last/data/transcription.txt"
  # path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech-lm-norm.txt"
  batch_size: *batch_size_value

codebook:
  model_name: "meta-llama/Llama-3.2-1B-Instruct"

encoder:
  # ckpt_path: "../weights/hubert_base_ls960.pt"
  ckpt_path: "../weights/convert_iter3.pt"
  encoder_embed_dim: 768
  frozen_layers: ["11", "10"]

downsample:
  kernel_size: &kernel_size_value 51
  stride: &stride_value 2
  groups: &groups_value 64

upsample:
  kernel_size: *kernel_size_value
  stride: *stride_value
  groups: *groups_value 

discriminator:
  hidden_dim: 256
  num_layers: 1


decoder:
  speaker:
    use_s : False
    use_postnet: False
    speaker_emb_dim: 512
    
  transformer:
    decoder_layer: 4
    decoder_head: 2
    decoder_hidden: 256
    conv_filter_size: 2048
    conv_kernel_size: [9, 1]
    decoder_dropout: 0.2
    dac_hidden: 1024
  max_seq_len: 2048

train:
  seed: 42121

  lr_enc: 0.00005
  lr_down: 0.00005
  lr_dec: 0.0001
  lr_disc: 0.0001
  grad_clip: 10.0
  
  num_steps: 100000
  freeze_steps: 100000
  discriminator_freq: 2
  gradient_accumulation_steps: 1

  mixed_precision: True
  resume_checkpoint: False
  resume_path: "checkpoints/step_10000.pth"


loss:
  recon_loss_weight: 1.0
  smooth_loss_weight: 0.1
  commit_loss_weight: 0.1
  gen_loss_weight: 0.0
  diversity_loss_weight: 1.0
  
  disc_loss_weight: 1.0
  gp_weight: 2.0

lr_scheduler:
  phase_ratio: [0.01, 0.2, 0.79]