checkpoint: 
  step: 10000

logging: 
  dir: "/raid/home/rajivratn/hemant_rajivratn/grpo/src/logs"
  step: 10

device: "cuda"

dataset_speech:
  train_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech/manifest/train.tsv"
  val_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech/manifest/val.tsv"
  test_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech/manifest/test.tsv"

  min_duration: 32000
  max_duration: 80000
  batch_size: &batch_size_value 32

dataset_txt:
  path: "/raid/home/rajivratn/hemant_rajivratn/last/data/txt/train.wrd"
  batch_size: *batch_size_value
  skip_non_speech: True

train:
  seed: 42123

  decoder_grad_scale: 0.001

  decoder: True
  teacher: False
  beta: 0.04

  temp: 1.0
  groups: 128 # this is the beam size.

  dlr: 0.0001
  lr: 0.00005
  grad_clip: 1.0
  
  steps: 100000
  freeze_epochs: 1
  accumulation_steps: 1

  resume_checkpoint: False
  resume_path: "checkpoints/step_10000.pth"

lr_scheduler:
  phase_ratio: [0.01, 0.0, 0.99]

codebook:
  # model_name: "meta-llama/Llama-3.2-1B"
  model_name: "gpt2"

encoder:
  ckpt_path: "/raid/home/rajivratn/hemant_rajivratn/last/weights/hubert_base_ls960.pt"
  # ckpt_path: "/raid/home/rajivratn/hemant_rajivratn/last/weights/convert_iter3.pt"
  encoder_embed_dim: 768
  frozen_layers: ["11"]

downsample:
  kernel_size: 5
  stride: 1
  groups: 128 # do not touch it is downsample


decoder:
  speaker:
    use_s : False
    speaker_emb_dim: 512
    
  transformer:
    decoder_layer: 4
    decoder_head: 2
    decoder_hidden: 256
    conv_filter_size: 1024
    conv_kernel_size: [9, 1]
    decoder_dropout: 0.2
    dac_hidden: 80
  max_seq_len: 2048
