checkpoint: 
  dir: "checkpoints"
  step: 5000

logging: 
  dir: "/raid/home/rajivratn/hemant_rajivratn/last/src/logs_5e-4_all"
  step: 100

device: "cuda"

dataset_speech:
  # train_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech/manifest/train.tsv"
  # val_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech/manifest/val.tsv"
  # test_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech/manifest/test.tsv"

  train_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/ljspeech/manifest/train.tsv"
  val_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/ljspeech/manifest/val.tsv"
  test_path: "/raid/home/rajivratn/hemant_rajivratn/last/data/ljspeech/manifest/test.tsv"

  min_duration: 32000
  max_duration: 320000
  batch_size: &batch_size_value 16


dataset_txt:
  path: "/raid/home/rajivratn/hemant_rajivratn/last/data/txt/train.wrd"
  # path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech-lm-norm.txt"
  batch_size: *batch_size_value

codebook:
  model_name: "meta-llama/Llama-3.2-1B-Instruct"

encoder:
  # ckpt_path: "../weights/hubert_base_ls960.pt"
  ckpt_path: "../weights/convert_iter3.pt"
  encoder_embed_dim: 768
  frozen_layers: ["11"]

downsample:
  kernel_size: &kernel_size_value 51
  stride: &stride_value 2
  groups: &groups_value 256

upsample:
  kernel_size: *kernel_size_value
  stride: *stride_value
  groups: *groups_value 

discriminator:
  hidden_dim: 256
  num_layers: 2


decoder:
  speaker:
    use_s : False
    speaker_emb_dim: 512
    
  transformer:
    decoder_layer: 4
    decoder_head: 2
    decoder_hidden: 256
    conv_filter_size: 2048
    conv_kernel_size: [9, 1]
    decoder_dropout: 0.2
    dac_hidden: 1024
  max_seq_len: 2048

train:
  seed: 42121
  train_vqvae: True
  train_disc: False
  train_full: False

  lr_enc: 0.00005
  lr_down: 0.0005
  lr_dec: 0.0005
  lr_disc: 0.0005
  grad_clip: 1.0
  
  num_steps: 50000
  freeze_steps: 100000
  gradient_accumulation_steps: 1
  discriminator_freq: 2

  mixed_precision: False
  resume_checkpoint: False
  resume_path: "checkpoints/step_10000.pth"

loss:
  recon_loss_weight: 1.0
  smooth_loss_weight: 1.0
  commit_loss_weight: 1.0
  gen_loss_weight: 1.0
  
  disc_loss_weight: 1.0
  gp_weight: 1.0

lr_scheduler:
  phase_ratio: [0.05, 0.05, 0.9]

eval:
  # eval: True
  eval: False

# Predicted CER: 0.7672, Real CER: 0.0404, Predicted WER: 1.0942, Real WER: 0.1425, STOI: 0.4142, rec_loss: 1.8403, commit_loss: 2.7035, smooth_loss: 0.1027
# Predicted CER: 0.7346, Real CER: 0.0404, Predicted WER: 1.0532, Real WER: 0.1425, STOI: 0.4322, rec_loss: 1.8208, commit_loss: 2.7122, smooth_loss: 0.1358
# Predicted CER: 0.6774, Real CER: 0.0404, Predicted WER: 0.9948, Real WER: 0.1425, STOI: 0.4248, rec_loss: 1.8354, commit_loss: 2.7194, smooth_loss: 0.1382
# Predicted CER: 0.7243, Real CER: 0.0404, Predicted WER: 1.0285, Real WER: 0.1425, STOI: 0.4258, rec_loss: 1.8412, commit_loss: 2.7175, smooth_loss: 0.1409
# Predicted CER: 0.7299, Real CER: 0.0404, Predicted WER: 1.0701, Real WER: 0.1425, STOI: 0.4146, rec_loss: 1.8549, commit_loss: 2.7244, smooth_loss: 0.1329
# Predicted CER: 0.6801, Real CER: 0.0404, Predicted WER: 1.0085, Real WER: 0.1425, STOI: 0.4111, rec_loss: 1.8614, commit_loss: 2.7322, smooth_loss: 0.1246
# Predicted CER: 0.7022, Real CER: 0.0404, Predicted WER: 0.9893, Real WER: 0.1425, STOI: 0.4016, rec_loss: 1.8743, commit_loss: 2.7269, smooth_loss: 0.1217
# Predicted CER: 0.7309, Real CER: 0.0404, Predicted WER: 1.0609, Real WER: 0.1425, STOI: 0.3966, rec_loss: 1.8824, commit_loss: 2.7439, smooth_loss: 0.1081
# Predicted CER: 0.7699, Real CER: 0.0404, Predicted WER: 1.0719, Real WER: 0.1425, STOI: 0.3919, rec_loss: 1.8913, commit_loss: 2.7524, smooth_loss: 0.1005
# Predicted CER: 0.8177, Real CER: 0.0404, Predicted WER: 1.0806, Real WER: 0.1425, STOI: 0.3895, rec_loss: 1.9004, commit_loss: 2.7585, smooth_loss: 0.0941

# Predicted CER: 0.6441, Real CER: 0.0404, Predicted WER: 0.9700, Real WER: 0.1425, STOI: 0.4771, rec_loss: 1.7719, commit_loss: 2.4581, smooth_loss: 0.7720
# Predicted CER: 0.6179, Real CER: 0.0404, Predicted WER: 0.8817, Real WER: 0.1425, STOI: 0.4865, rec_loss: 1.7587, commit_loss: 2.4642, smooth_loss: 0.8170
# Predicted CER: 0.5668, Real CER: 0.0404, Predicted WER: 0.8487, Real WER: 0.1425, STOI: 0.4879, rec_loss: 1.7549, commit_loss: 2.4671, smooth_loss: 0.8852
# Predicted CER: 0.5139, Real CER: 0.0404, Predicted WER: 0.7975, Real WER: 0.1425, STOI: 0.4948, rec_loss: 1.7474, commit_loss: 2.4672, smooth_loss: 0.8967
# Predicted CER: 0.4902, Real CER: 0.0404, Predicted WER: 0.7948, Real WER: 0.1425, STOI: 0.4930, rec_loss: 1.7451, commit_loss: 2.4708, smooth_loss: 0.8761
# Predicted CER: 0.4671, Real CER: 0.0404, Predicted WER: 0.7518, Real WER: 0.1425, STOI: 0.5023, rec_loss: 1.7394, commit_loss: 2.4681, smooth_loss: 0.8886