dataset_speech:
  # path: "/raid/home/rajivratn/hemant_rajivratn/librispeech/data/manifest/train-clean-100.tsv"
  path: "/raid/home/rajivratn/hemant_rajivratn/last/data/ljspeechmanifest.tsv"

dataset_txt:
  path: "/raid/home/rajivratn/hemant_rajivratn/last/data/transcription.txt"
  # path: "/raid/home/rajivratn/hemant_rajivratn/last/data/librispeech-lm-norm.txt"

encoder:
  ckpt_path: "hubert_base_ls960.pt"

downsample:
  kernel_size: 1
  stride: &stride_value 2

upsample:
  kernel_size: 1
  stride: *stride_value

decoder:
  speaker:
    use_s : False
    speaker_emb_dim: 512
  transformer:
    decoder_layer: 4
    decoder_head: 2
    decoder_hidden: 256
    conv_filter_size: 2048
    conv_kernel_size: [9, 1]
    decoder_dropout: 0.2
    dac_hidden: 1024
  max_seq_len: 1000

discriminator:
  hidden_dim: 256
  kernel_size: 9


train: 
  lr_enc: 0.00005
  lr_down: 0.0005
  lr_dec: 0.0005
  lr_disc: 0.0005
  num_steps: 10000

  freez_steps: 10000

loss:
  recon_loss_weight: 1.0
  smooth_loss_weight: 1.0
  commit_loss_weight: 100.0
  diversity_loss_weight: .5
  gen_loss_weight: 1.0

  disc_loss_weight: 1.0
  gp_weight: 1.0

